# Generated by Django 3.2.9 on 2022-03-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='categoty',
            new_name='category',
        ),
    ]
