# Generated by Django 3.2.9 on 2022-03-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name_plural': 'User Preferences'},
        ),
    ]
